### PR TITLE
Add Modal Confirm

### PR DESCRIPTION
**Pull request by raczyk**

### CODE REVIEW

**Comment by khola** [comment]
image

Why is this margin so big?

**Comment by raczyk** [comment]
I think it looks better with message closer to the bottom than to the top.
Screenshot 2020-07-21 at 16 41 30

**Comment by Horay** [comment]
Screenshot 2020-07-21 at 17 02 30

I have updated the Figma mockup and there you have all styles

**Comment by raczyk** [comment]
Done :)

**Pull request merged**
